<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/pages/common/include.jsp"%>   
<youi:page styleClass="bg-white"> 
	<div class="col-sm-2"><span class="youi-icon icon-star-empty"></span>	icon-star-empty</div>
	<div class="col-sm-2"><span class="youi-icon icon-user"></span>	icon-user</div>
	<div class="col-sm-2"><span class="youi-icon icon-film"></span>	icon-film</div>
	<div class="col-sm-2"><span class="youi-icon icon-th-large"></span>	icon-th-large</div>
	<div class="col-sm-2"><span class="youi-icon icon-th"></span>	icon-th</div>
	<div class="col-sm-2"><span class="youi-icon icon-th-list"></span>	icon-th-list</div>
	<div class="col-sm-2"><span class="youi-icon icon-ok"></span>	icon-ok</div>
	<div class="col-sm-2"><span class="youi-icon icon-remove"></span>	icon-remove</div>
	<div class="col-sm-2"><span class="youi-icon icon-zoom-in"></span>	icon-zoom-in</div>
	<div class="col-sm-2"><span class="youi-icon icon-zoom-out"></span>	icon-zoom-out</div>
	<div class="col-sm-2"><span class="youi-icon icon-power-off"></span>	icon-power-off	icon-off	</div>
	<div class="col-sm-2"><span class="youi-icon icon-signal"></span>	icon-signal</div>
	<div class="col-sm-2"><span class="youi-icon icon-gear"></span>	icon-gear	icon-cog	</div>
	<div class="col-sm-2"><span class="youi-icon icon-trash"></span>	icon-trash</div>
	<div class="col-sm-2"><span class="youi-icon icon-home"></span>	icon-home</div>
	<div class="col-sm-2"><span class="youi-icon icon-file-alt"></span>	icon-file-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-time"></span>	icon-time</div>
	<div class="col-sm-2"><span class="youi-icon icon-road"></span>	icon-road</div>
	<div class="col-sm-2"><span class="youi-icon icon-download-alt"></span>	icon-download-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-download"></span>	icon-download</div>
	<div class="col-sm-2"><span class="youi-icon icon-upload"></span>	icon-upload</div>
	<div class="col-sm-2"><span class="youi-icon icon-inbox"></span>	icon-inbox</div>
	<div class="col-sm-2"><span class="youi-icon icon-play-circle"></span>	icon-play-circle</div>
	<div class="col-sm-2"><span class="youi-icon icon-rotate-right"></span>	icon-rotate-right	icon-repeat	</div>
	<div class="col-sm-2"><span class="youi-icon icon-refresh"></span>	icon-refresh</div>
	<div class="col-sm-2"><span class="youi-icon icon-list-alt"></span>	icon-list-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-lock"></span>	icon-lock</div>
	<div class="col-sm-2"><span class="youi-icon icon-flag"></span>	icon-flag</div>
	<div class="col-sm-2"><span class="youi-icon icon-headphones"></span>	icon-headphones</div>
	<div class="col-sm-2"><span class="youi-icon icon-volume-off"></span>	icon-volume-off</div>
	<div class="col-sm-2"><span class="youi-icon icon-volume-down"></span>	icon-volume-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-volume-up"></span>	icon-volume-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-qrcode"></span>	icon-qrcode</div>
	<div class="col-sm-2"><span class="youi-icon icon-barcode"></span>	icon-barcode</div>
	<div class="col-sm-2"><span class="youi-icon icon-tag"></span>	icon-tag</div>
	<div class="col-sm-2"><span class="youi-icon icon-tags"></span>	icon-tags</div>
	<div class="col-sm-2"><span class="youi-icon icon-book"></span>	icon-book</div>
	<div class="col-sm-2"><span class="youi-icon icon-bookmark"></span>	icon-bookmark</div>
	<div class="col-sm-2"><span class="youi-icon icon-print"></span>	icon-print</div>
	<div class="col-sm-2"><span class="youi-icon icon-camera"></span>	icon-camera</div>
	<div class="col-sm-2"><span class="youi-icon icon-font"></span>	icon-font</div>
	<div class="col-sm-2"><span class="youi-icon icon-bold"></span>	icon-bold</div>
	<div class="col-sm-2"><span class="youi-icon icon-italic"></span>	icon-italic</div>
	<div class="col-sm-2"><span class="youi-icon icon-text-height"></span>	icon-text-height</div>
	<div class="col-sm-2"><span class="youi-icon icon-text-width"></span>	icon-text-width</div>
	<div class="col-sm-2"><span class="youi-icon icon-align-left"></span>	icon-align-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-align-center"></span>	icon-align-center</div>
	<div class="col-sm-2"><span class="youi-icon icon-align-right"></span>	icon-align-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-align-justify"></span>	icon-align-justify</div>
	<div class="col-sm-2"><span class="youi-icon icon-list"></span>	icon-list</div>
	<div class="col-sm-2"><span class="youi-icon icon-indent-left"></span>	icon-indent-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-indent-right"></span>	icon-indent-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-facetime-video"></span>	icon-facetime-video</div>
	<div class="col-sm-2"><span class="youi-icon icon-picture"></span>	icon-picture</div>
	<div class="col-sm-2"><span class="youi-icon icon-pencil"></span>	icon-pencil</div>
	<div class="col-sm-2"><span class="youi-icon icon-map-marker"></span>	icon-map-marker</div>
	<div class="col-sm-2"><span class="youi-icon icon-adjust"></span>	icon-adjust</div>
	<div class="col-sm-2"><span class="youi-icon icon-tint"></span>	icon-tint</div>
	<div class="col-sm-2"><span class="youi-icon icon-edit"></span>	icon-edit</div>
	<div class="col-sm-2"><span class="youi-icon icon-share"></span>	icon-share</div>
	<div class="col-sm-2"><span class="youi-icon icon-check"></span>	icon-check</div>
	<div class="col-sm-2"><span class="youi-icon icon-move"></span>	icon-move</div>
	<div class="col-sm-2"><span class="youi-icon icon-step-backward"></span>	icon-step-backward</div>
	<div class="col-sm-2"><span class="youi-icon icon-fast-backward"></span>	icon-fast-backward</div>
	<div class="col-sm-2"><span class="youi-icon icon-backward"></span>	icon-backward</div>
	<div class="col-sm-2"><span class="youi-icon icon-play"></span>	icon-play</div>
	<div class="col-sm-2"><span class="youi-icon icon-pause"></span>	icon-pause</div>
	<div class="col-sm-2"><span class="youi-icon icon-stop"></span>	icon-stop</div>
	<div class="col-sm-2"><span class="youi-icon icon-forward"></span>	icon-forward</div>
	<div class="col-sm-2"><span class="youi-icon icon-fast-forward"></span>	icon-fast-forward</div>
	<div class="col-sm-2"><span class="youi-icon icon-step-forward"></span>	icon-step-forward</div>
	<div class="col-sm-2"><span class="youi-icon icon-eject"></span>	icon-eject</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-left"></span>	icon-chevron-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-right"></span>	icon-chevron-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-plus-sign"></span>	icon-plus-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-minus-sign"></span>	icon-minus-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-remove-sign"></span>	icon-remove-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-ok-sign"></span>	icon-ok-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-question-sign"></span>	icon-question-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-info-sign"></span>	icon-info-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-screenshot"></span>	icon-screenshot</div>
	<div class="col-sm-2"><span class="youi-icon icon-remove-circle"></span>	icon-remove-circle</div>
	<div class="col-sm-2"><span class="youi-icon icon-ok-circle"></span>	icon-ok-circle</div>
	<div class="col-sm-2"><span class="youi-icon icon-ban-circle"></span>	icon-ban-circle</div>
	<div class="col-sm-2"><span class="youi-icon icon-arrow-left"></span>	icon-arrow-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-arrow-right"></span>	icon-arrow-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-arrow-up"></span>	icon-arrow-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-arrow-down"></span>	icon-arrow-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-mail-forward"></span>	icon-mail-forward	icon-share-alt	</div>
	<div class="col-sm-2"><span class="youi-icon icon-resize-full"></span>	icon-resize-full</div>
	<div class="col-sm-2"><span class="youi-icon icon-resize-small"></span>	icon-resize-small</div>
	<div class="col-sm-2"><span class="youi-icon icon-plus"></span>	icon-plus</div>
	<div class="col-sm-2"><span class="youi-icon icon-minus"></span>	icon-minus</div>
	<div class="col-sm-2"><span class="youi-icon icon-asterisk"></span>	icon-asterisk</div>
	<div class="col-sm-2"><span class="youi-icon icon-exclamation-sign"></span>	icon-exclamation-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-gift"></span>	icon-gift</div>
	<div class="col-sm-2"><span class="youi-icon icon-leaf"></span>	icon-leaf</div>
	<div class="col-sm-2"><span class="youi-icon icon-fire"></span>	icon-fire</div>
	<div class="col-sm-2"><span class="youi-icon icon-eye-open"></span>	icon-eye-open</div>
	<div class="col-sm-2"><span class="youi-icon icon-eye-close"></span>	icon-eye-close</div>
	<div class="col-sm-2"><span class="youi-icon icon-warning-sign"></span>	icon-warning-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-plane"></span>	icon-plane</div>
	<div class="col-sm-2"><span class="youi-icon icon-calendar"></span>	icon-calendar</div>
	<div class="col-sm-2"><span class="youi-icon icon-random"></span>	icon-random</div>
	<div class="col-sm-2"><span class="youi-icon icon-comment"></span>	icon-comment</div>
	<div class="col-sm-2"><span class="youi-icon icon-magnet"></span>	icon-magnet</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-up"></span>	icon-chevron-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-down"></span>	icon-chevron-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-retweet"></span>	icon-retweet</div>
	<div class="col-sm-2"><span class="youi-icon icon-shopping-cart"></span>	icon-shopping-cart</div>
	<div class="col-sm-2"><span class="youi-icon icon-folder-close"></span>	icon-folder-close</div>
	<div class="col-sm-2"><span class="youi-icon icon-folder-open"></span>	icon-folder-open</div>
	<div class="col-sm-2"><span class="youi-icon icon-resize-vertical"></span>	icon-resize-vertical</div>
	<div class="col-sm-2"><span class="youi-icon icon-resize-horizontal"></span>	icon-resize-horizontal</div>
	<div class="col-sm-2"><span class="youi-icon icon-bar-chart"></span>	icon-bar-chart</div>
	<div class="col-sm-2"><span class="youi-icon icon-twitter-sign"></span>	icon-twitter-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-facebook-sign"></span>	icon-facebook-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-camera-retro"></span>	icon-camera-retro</div>
	<div class="col-sm-2"><span class="youi-icon icon-key"></span>	icon-key</div>
	<div class="col-sm-2"><span class="youi-icon icon-gears"></span>	icon-gears	icon-cogs	</div>
	<div class="col-sm-2"><span class="youi-icon icon-comments"></span>	icon-comments</div>
	<div class="col-sm-2"><span class="youi-icon icon-thumbs-up-alt"></span>	icon-thumbs-up-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-thumbs-down-alt"></span>	icon-thumbs-down-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-star-half"></span>	icon-star-half</div>
	<div class="col-sm-2"><span class="youi-icon icon-heart-empty"></span>	icon-heart-empty</div>
	<div class="col-sm-2"><span class="youi-icon icon-signout"></span>	icon-signout</div>
	<div class="col-sm-2"><span class="youi-icon icon-linkedin-sign"></span>	icon-linkedin-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-pushpin"></span>	icon-pushpin</div>
	<div class="col-sm-2"><span class="youi-icon icon-external-link"></span>	icon-external-link</div>
	<div class="col-sm-2"><span class="youi-icon icon-signin"></span>	icon-signin</div>
	<div class="col-sm-2"><span class="youi-icon icon-trophy"></span>	icon-trophy</div>
	<div class="col-sm-2"><span class="youi-icon icon-github-sign"></span>	icon-github-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-upload-alt"></span>	icon-upload-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-lemon"></span>	icon-lemon</div>
	<div class="col-sm-2"><span class="youi-icon icon-phone"></span>	icon-phone</div>
	<div class="col-sm-2"><span class="youi-icon icon-unchecked"></span>	icon-unchecked	icon-check-empty	</div>
	<div class="col-sm-2"><span class="youi-icon icon-bookmark-empty"></span>	icon-bookmark-empty</div>
	<div class="col-sm-2"><span class="youi-icon icon-phone-sign"></span>	icon-phone-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-twitter"></span>	icon-twitter</div>
	<div class="col-sm-2"><span class="youi-icon icon-facebook"></span>	icon-facebook</div>
	<div class="col-sm-2"><span class="youi-icon icon-github"></span>	icon-github</div>
	<div class="col-sm-2"><span class="youi-icon icon-unlock"></span>	icon-unlock</div>
	<div class="col-sm-2"><span class="youi-icon icon-credit-card"></span>	icon-credit-card</div>
	<div class="col-sm-2"><span class="youi-icon icon-rss"></span>	icon-rss</div>
	<div class="col-sm-2"><span class="youi-icon icon-hdd"></span>	icon-hdd</div>
	<div class="col-sm-2"><span class="youi-icon icon-bullhorn"></span>	icon-bullhorn</div>
	<div class="col-sm-2"><span class="youi-icon icon-bell"></span>	icon-bell</div>
	<div class="col-sm-2"><span class="youi-icon icon-certificate"></span>	icon-certificate</div>
	<div class="col-sm-2"><span class="youi-icon icon-hand-right"></span>	icon-hand-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-hand-left"></span>	icon-hand-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-hand-up"></span>	icon-hand-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-hand-down"></span>	icon-hand-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-circle-arrow-left"></span>	icon-circle-arrow-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-circle-arrow-right"></span>	icon-circle-arrow-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-circle-arrow-up"></span>	icon-circle-arrow-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-circle-arrow-down"></span>	icon-circle-arrow-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-globe"></span>	icon-globe</div>
	<div class="col-sm-2"><span class="youi-icon icon-wrench"></span>	icon-wrench</div>
	<div class="col-sm-2"><span class="youi-icon icon-tasks"></span>	icon-tasks</div>
	<div class="col-sm-2"><span class="youi-icon icon-filter"></span>	icon-filter</div>
	<div class="col-sm-2"><span class="youi-icon icon-briefcase"></span>	icon-briefcase</div>
	<div class="col-sm-2"><span class="youi-icon icon-fullscreen"></span>	icon-fullscreen</div>
	<div class="col-sm-2"><span class="youi-icon icon-group"></span>	icon-group</div>
	<div class="col-sm-2"><span class="youi-icon icon-link"></span>	icon-link</div>
	<div class="col-sm-2"><span class="youi-icon icon-cloud"></span>	icon-cloud</div>
	<div class="col-sm-2"><span class="youi-icon icon-beaker"></span>	icon-beaker</div>
	<div class="col-sm-2"><span class="youi-icon icon-cut"></span>	icon-cut</div>
	<div class="col-sm-2"><span class="youi-icon icon-copy"></span>	icon-copy</div>
	<div class="col-sm-2"><span class="youi-icon icon-paperclip"></span>	icon-paperclip	icon-paper-clip	</div>
	<div class="col-sm-2"><span class="youi-icon icon-save"></span>	icon-save</div>
	<div class="col-sm-2"><span class="youi-icon icon-sign-blank"></span>	icon-sign-blank</div>
	<div class="col-sm-2"><span class="youi-icon icon-reorder"></span>	icon-reorder</div>
	<div class="col-sm-2"><span class="youi-icon icon-list-ul"></span>	icon-list-ul</div>
	<div class="col-sm-2"><span class="youi-icon icon-list-ol"></span>	icon-list-ol</div>
	<div class="col-sm-2"><span class="youi-icon icon-strikethrough"></span>	icon-strikethrough</div>
	<div class="col-sm-2"><span class="youi-icon icon-underline"></span>	icon-underline</div>
	<div class="col-sm-2"><span class="youi-icon icon-table"></span>	icon-table</div>
	<div class="col-sm-2"><span class="youi-icon icon-magic"></span>	icon-magic</div>
	<div class="col-sm-2"><span class="youi-icon icon-truck"></span>	icon-truck</div>
	<div class="col-sm-2"><span class="youi-icon icon-pinterest"></span>	icon-pinterest</div>
	<div class="col-sm-2"><span class="youi-icon icon-pinterest-sign"></span>	icon-pinterest-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-google-plus-sign"></span>	icon-google-plus-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-google-plus"></span>	icon-google-plus</div>
	<div class="col-sm-2"><span class="youi-icon icon-money"></span>	icon-money</div>
	<div class="col-sm-2"><span class="youi-icon icon-caret-down"></span>	icon-caret-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-caret-up"></span>	icon-caret-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-caret-left"></span>	icon-caret-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-caret-right"></span>	icon-caret-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-columns"></span>	icon-columns</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort"></span>	icon-sort</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-down"></span>	icon-sort-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-up"></span>	icon-sort-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-envelope"></span>	icon-envelope</div>
	<div class="col-sm-2"><span class="youi-icon icon-linkedin"></span>	icon-linkedin</div>
	<div class="col-sm-2"><span class="youi-icon icon-rotate-left"></span>	icon-rotate-left	icon-undo	</div>
	<div class="col-sm-2"><span class="youi-icon icon-legal"></span>	icon-legal</div>
	<div class="col-sm-2"><span class="youi-icon icon-dashboard"></span>	icon-dashboard</div>
	<div class="col-sm-2"><span class="youi-icon icon-comment-alt"></span>	icon-comment-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-comments-alt"></span>	icon-comments-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-bolt"></span>	icon-bolt</div>
	<div class="col-sm-2"><span class="youi-icon icon-sitemap"></span>	icon-sitemap</div>
	<div class="col-sm-2"><span class="youi-icon icon-umbrella"></span>	icon-umbrella</div>
	<div class="col-sm-2"><span class="youi-icon icon-paste"></span>	icon-paste</div>
	<div class="col-sm-2"><span class="youi-icon icon-lightbulb"></span>	icon-lightbulb</div>
	<div class="col-sm-2"><span class="youi-icon icon-exchange"></span>	icon-exchange</div>
	<div class="col-sm-2"><span class="youi-icon icon-cloud-download"></span>	icon-cloud-download</div>
	<div class="col-sm-2"><span class="youi-icon icon-cloud-upload"></span>	icon-cloud-upload</div>
	<div class="col-sm-2"><span class="youi-icon icon-user-md"></span>	icon-user-md</div>
	<div class="col-sm-2"><span class="youi-icon icon-stethoscope"></span>	icon-stethoscope</div>
	<div class="col-sm-2"><span class="youi-icon icon-suitcase"></span>	icon-suitcase</div>
	<div class="col-sm-2"><span class="youi-icon icon-bell-alt"></span>	icon-bell-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-coffee"></span>	icon-coffee</div>
	<div class="col-sm-2"><span class="youi-icon icon-food"></span>	icon-food</div>
	<div class="col-sm-2"><span class="youi-icon icon-file-text-alt"></span>	icon-file-text-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-building"></span>	icon-building</div>
	<div class="col-sm-2"><span class="youi-icon icon-hospital"></span>	icon-hospital</div>
	<div class="col-sm-2"><span class="youi-icon icon-ambulance"></span>	icon-ambulance</div>
	<div class="col-sm-2"><span class="youi-icon icon-medkit"></span>	icon-medkit</div>
	<div class="col-sm-2"><span class="youi-icon icon-fighter-jet"></span>	icon-fighter-jet</div>
	<div class="col-sm-2"><span class="youi-icon icon-beer"></span>	icon-beer</div>
	<div class="col-sm-2"><span class="youi-icon icon-h-sign"></span>	icon-h-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-plus-sign-alt"></span>	icon-plus-sign-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-double-angle-left"></span>	icon-double-angle-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-double-angle-right"></span>	icon-double-angle-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-double-angle-up"></span>	icon-double-angle-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-double-angle-down"></span>	icon-double-angle-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-angle-left"></span>	icon-angle-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-angle-right"></span>	icon-angle-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-angle-up"></span>	icon-angle-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-angle-down"></span>	icon-angle-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-desktop"></span>	icon-desktop</div>
	<div class="col-sm-2"><span class="youi-icon icon-laptop"></span>	icon-laptop</div>
	<div class="col-sm-2"><span class="youi-icon icon-tablet"></span>	icon-tablet</div>
	<div class="col-sm-2"><span class="youi-icon icon-mobile-phone"></span>	icon-mobile-phone</div>
	<div class="col-sm-2"><span class="youi-icon icon-circle-blank"></span>	icon-circle-blank</div>
	<div class="col-sm-2"><span class="youi-icon icon-quote-left"></span>	icon-quote-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-quote-right"></span>	icon-quote-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-spinner"></span>	icon-spinner</div>
	<div class="col-sm-2"><span class="youi-icon icon-circle"></span>	icon-circle</div>
	<div class="col-sm-2"><span class="youi-icon icon-mail-reply"></span>	icon-mail-reply	icon-reply	</div>
	<div class="col-sm-2"><span class="youi-icon icon-github-alt"></span>	icon-github-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-folder-close-alt"></span>	icon-folder-close-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-folder-open-alt"></span>	icon-folder-open-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-expand-alt"></span>	icon-expand-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-collapse-alt"></span>	icon-collapse-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-smile"></span>	icon-smile</div>
	<div class="col-sm-2"><span class="youi-icon icon-frown"></span>	icon-frown</div>
	<div class="col-sm-2"><span class="youi-icon icon-meh"></span>	icon-meh</div>
	<div class="col-sm-2"><span class="youi-icon icon-gamepad"></span>	icon-gamepad</div>
	<div class="col-sm-2"><span class="youi-icon icon-keyboard"></span>	icon-keyboard</div>
	<div class="col-sm-2"><span class="youi-icon icon-flag-alt"></span>	icon-flag-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-flag-checkered"></span>	icon-flag-checkered</div>
	<div class="col-sm-2"><span class="youi-icon icon-terminal"></span>	icon-terminal</div>
	<div class="col-sm-2"><span class="youi-icon icon-code"></span>	icon-code</div>
	<div class="col-sm-2"><span class="youi-icon icon-reply-all"></span>	icon-reply-all</div>
	<div class="col-sm-2"><span class="youi-icon icon-mail-reply-all"></span>	icon-mail-reply-all</div>
	<div class="col-sm-2"><span class="youi-icon icon-star-half-full"></span>	icon-star-half-full	icon-star-half-empty	</div>
	<div class="col-sm-2"><span class="youi-icon icon-location-arrow"></span>	icon-location-arrow</div>
	<div class="col-sm-2"><span class="youi-icon icon-crop"></span>	icon-crop</div>
	<div class="col-sm-2"><span class="youi-icon icon-code-fork"></span>	icon-code-fork</div>
	<div class="col-sm-2"><span class="youi-icon icon-unlink"></span>	icon-unlink</div>
	<div class="col-sm-2"><span class="youi-icon icon-question"></span>	icon-question</div>
	<div class="col-sm-2"><span class="youi-icon icon-info"></span>	icon-info</div>
	<div class="col-sm-2"><span class="youi-icon icon-exclamation"></span>	icon-exclamation</div>
	<div class="col-sm-2"><span class="youi-icon icon-superscript"></span>	icon-superscript</div>
	<div class="col-sm-2"><span class="youi-icon icon-subscript"></span>	icon-subscript</div>
	<div class="col-sm-2"><span class="youi-icon icon-eraser"></span>	icon-eraser</div>
	<div class="col-sm-2"><span class="youi-icon icon-puzzle-piece"></span>	icon-puzzle-piece</div>
	<div class="col-sm-2"><span class="youi-icon icon-microphone"></span>	icon-microphone</div>
	<div class="col-sm-2"><span class="youi-icon icon-microphone-off"></span>	icon-microphone-off</div>
	<div class="col-sm-2"><span class="youi-icon icon-shield"></span>	icon-shield</div>
	<div class="col-sm-2"><span class="youi-icon icon-calendar-empty"></span>	icon-calendar-empty</div>
	<div class="col-sm-2"><span class="youi-icon icon-fire-extinguisher"></span>	icon-fire-extinguisher</div>
	<div class="col-sm-2"><span class="youi-icon icon-rocket"></span>	icon-rocket</div>
	<div class="col-sm-2"><span class="youi-icon icon-maxcdn"></span>	icon-maxcdn</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-sign-left"></span>	icon-chevron-sign-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-sign-right"></span>	icon-chevron-sign-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-sign-up"></span>	icon-chevron-sign-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-chevron-sign-down"></span>	icon-chevron-sign-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-html5"></span>	icon-html5</div>
	<div class="col-sm-2"><span class="youi-icon icon-css3"></span>	icon-css3</div>
	<div class="col-sm-2"><span class="youi-icon icon-anchor"></span>	icon-anchor</div>
	<div class="col-sm-2"><span class="youi-icon icon-unlock-alt"></span>	icon-unlock-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-bullseye"></span>	icon-bullseye</div>
	<div class="col-sm-2"><span class="youi-icon icon-ellipsis-horizontal"></span>	icon-ellipsis-horizontal</div>
	<div class="col-sm-2"><span class="youi-icon icon-ellipsis-vertical"></span>	icon-ellipsis-vertical</div>
	<div class="col-sm-2"><span class="youi-icon icon-rss-sign"></span>	icon-rss-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-play-sign"></span>	icon-play-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-ticket"></span>	icon-ticket</div>
	<div class="col-sm-2"><span class="youi-icon icon-minus-sign-alt"></span>	icon-minus-sign-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-check-minus"></span>	icon-check-minus</div>
	<div class="col-sm-2"><span class="youi-icon icon-level-up"></span>	icon-level-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-level-down"></span>	icon-level-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-check-sign"></span>	icon-check-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-edit-sign"></span>	icon-edit-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-external-link-sign"></span>	icon-external-link-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-share-sign"></span>	icon-share-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-compass"></span>	icon-compass</div>
	<div class="col-sm-2"><span class="youi-icon icon-collapse"></span>	icon-collapse</div>
	<div class="col-sm-2"><span class="youi-icon icon-collapse-top"></span>	icon-collapse-top</div>
	<div class="col-sm-2"><span class="youi-icon icon-expand"></span>	icon-expand</div>
	<div class="col-sm-2"><span class="youi-icon icon-euro"></span>	icon-euro	icon-eur	</div>
	<div class="col-sm-2"><span class="youi-icon icon-gbp"></span>	icon-gbp</div>
	<div class="col-sm-2"><span class="youi-icon icon-dollar"></span>	icon-dollar	icon-usd	</div>
	<div class="col-sm-2"><span class="youi-icon icon-rupee"></span>	icon-rupee	icon-inr	</div>
	<div class="col-sm-2"><span class="youi-icon icon-yen"></span>	icon-yen	icon-jpy	</div>
	<div class="col-sm-2"><span class="youi-icon icon-renminbi"></span>	icon-renminbi	icon-cny	</div>
	<div class="col-sm-2"><span class="youi-icon icon-won"></span>	icon-won	icon-krw	</div>
	<div class="col-sm-2"><span class="youi-icon icon-bitcoin"></span>	icon-bitcoin	icon-btc	</div>
	<div class="col-sm-2"><span class="youi-icon icon-file"></span>	icon-file</div>
	<div class="col-sm-2"><span class="youi-icon icon-file-text"></span>	icon-file-text</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-by-alphabet"></span>	icon-sort-by-alphabet</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-by-alphabet-alt"></span>	icon-sort-by-alphabet-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-by-attributes"></span>	icon-sort-by-attributes</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-by-attributes-alt"></span>	icon-sort-by-attributes-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-by-order"></span>	icon-sort-by-order</div>
	<div class="col-sm-2"><span class="youi-icon icon-sort-by-order-alt"></span>	icon-sort-by-order-alt</div>
	<div class="col-sm-2"><span class="youi-icon icon-thumbs-up"></span>	icon-thumbs-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-thumbs-down"></span>	icon-thumbs-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-youtube-sign"></span>	icon-youtube-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-youtube"></span>	icon-youtube</div>
	<div class="col-sm-2"><span class="youi-icon icon-xing"></span>	icon-xing</div>
	<div class="col-sm-2"><span class="youi-icon icon-xing-sign"></span>	icon-xing-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-youtube-play"></span>	icon-youtube-play</div>
	<div class="col-sm-2"><span class="youi-icon icon-dropbox"></span>	icon-dropbox</div>
	<div class="col-sm-2"><span class="youi-icon icon-stackexchange"></span>	icon-stackexchange</div>
	<div class="col-sm-2"><span class="youi-icon icon-instagram"></span>	icon-instagram</div>
	<div class="col-sm-2"><span class="youi-icon icon-flickr"></span>	icon-flickr</div>
	<div class="col-sm-2"><span class="youi-icon icon-adn"></span>	icon-adn</div>
	<div class="col-sm-2"><span class="youi-icon icon-bitbucket"></span>	icon-bitbucket</div>
	<div class="col-sm-2"><span class="youi-icon icon-bitbucket-sign"></span>	icon-bitbucket-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-tumblr"></span>	icon-tumblr</div>
	<div class="col-sm-2"><span class="youi-icon icon-tumblr-sign"></span>	icon-tumblr-sign</div>
	<div class="col-sm-2"><span class="youi-icon icon-long-arrow-down"></span>	icon-long-arrow-down</div>
	<div class="col-sm-2"><span class="youi-icon icon-long-arrow-up"></span>	icon-long-arrow-up</div>
	<div class="col-sm-2"><span class="youi-icon icon-long-arrow-left"></span>	icon-long-arrow-left</div>
	<div class="col-sm-2"><span class="youi-icon icon-long-arrow-right"></span>	icon-long-arrow-right</div>
	<div class="col-sm-2"><span class="youi-icon icon-apple"></span>	icon-apple</div>
	<div class="col-sm-2"><span class="youi-icon icon-windows"></span>	icon-windows</div>
	<div class="col-sm-2"><span class="youi-icon icon-android"></span>	icon-android</div>
	<div class="col-sm-2"><span class="youi-icon icon-linux"></span>	icon-linux</div>
	<div class="col-sm-2"><span class="youi-icon icon-dribbble"></span>	icon-dribbble</div>
	<div class="col-sm-2"><span class="youi-icon icon-skype"></span>	icon-skype</div>
	<div class="col-sm-2"><span class="youi-icon icon-foursquare"></span>	icon-foursquare</div>
	<div class="col-sm-2"><span class="youi-icon icon-trello"></span>	icon-trello</div>
	<div class="col-sm-2"><span class="youi-icon icon-female"></span>	icon-female</div>
	<div class="col-sm-2"><span class="youi-icon icon-male"></span>	icon-male</div>
	<div class="col-sm-2"><span class="youi-icon icon-gittip"></span>	icon-gittip</div>
	<div class="col-sm-2"><span class="youi-icon icon-sun"></span>	icon-sun</div>
	<div class="col-sm-2"><span class="youi-icon icon-moon"></span>	icon-moon</div>
	<div class="col-sm-2"><span class="youi-icon icon-archive"></span>	icon-archive</div>
	<div class="col-sm-2"><span class="youi-icon icon-bug"></span>	icon-bug</div>
	<div class="col-sm-2"><span class="youi-icon icon-vk"></span>	icon-vk</div>
	<div class="col-sm-2"><span class="youi-icon icon-weibo"></span>	icon-weibo</div>
	<div class="col-sm-2"><span class="youi-icon icon-renren"></span>	icon-renren</div>
</youi:page> 